"""initial schema

Revision ID: fd8f166993a0
Revises: 
Create Date: 2026-07-01 12:03:55.500943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd8f166993a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_normalized_name'), 'authors', ['normalized_name'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('arxiv_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('primary_category', sa.String(length=50), nullable=True),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('abs_url', sa.Text(), nullable=True),
    sa.Column('pdf_local_path', sa.Text(), nullable=True),
    sa.Column('parse_status', sa.Enum('PENDING', 'PARSED', 'LOW_TEXT', 'FAILED', name='parsestatus', native_enum=False), nullable=False),
    sa.Column('chunking_strategy', sa.Enum('FIXED_SIZE', 'PARAGRAPH', 'SECTION_AWARE', 'PARENT_CHILD', name='chunkingstrategy', native_enum=False), nullable=True),
    sa.Column('source', sa.Enum('ARXIV', 'WIKIPEDIA', name='documentsource', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_arxiv_id'), 'documents', ['arxiv_id'], unique=True)
    op.create_index(op.f('ix_documents_primary_category'), 'documents', ['primary_category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('scope', sa.Enum('SINGLE_PAPER', 'MULTI_PAPER', 'GENERAL', name='conversationscope', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('document_authors',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('author_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'author_id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunking_strategy', sa.Enum('FIXED_SIZE', 'PARAGRAPH', 'SECTION_AWARE', 'PARENT_CHILD', name='chunkingstrategy', native_enum=False), nullable=False),
    sa.Column('chunk_level', sa.Enum('LEAF', 'PARENT', 'CHILD', name='chunklevel', native_enum=False), nullable=False),
    sa.Column('parent_chunk_id', sa.Uuid(), nullable=True),
    sa.Column('section_type', sa.Enum('ABSTRACT', 'INTRODUCTION', 'RELATED_WORK', 'METHODOLOGY', 'EXPERIMENTS', 'RESULTS', 'DISCUSSION', 'CONCLUSION', 'LIMITATIONS', 'REFERENCES', 'OTHER', name='sectiontype', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_chunks_content_tsv', 'document_chunks', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_parent_chunk_id'), 'document_chunks', ['parent_chunk_id'], unique=False)
    op.create_index('ix_document_chunks_section_type', 'document_chunks', ['section_type'], unique=False)
    op.create_table('document_views',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('view_type', sa.Enum('SEARCH_RESULT_CLICK', 'DETAIL_OPEN', 'CHAT_REFERENCE', 'COMPARE', name='viewtype', native_enum=False), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_views_document_id'), 'document_views', ['document_id'], unique=False)
    op.create_index('ix_document_views_user_document', 'document_views', ['user_id', 'document_id'], unique=False)
    op.create_index(op.f('ix_document_views_user_id'), 'document_views', ['user_id'], unique=False)
    op.create_index('ix_document_views_user_viewed', 'document_views', ['user_id', 'viewed_at'], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('search_type', sa.Enum('SEMANTIC', 'KEYWORD', 'HYBRID', name='searchtype', native_enum=False), nullable=False),
    sa.Column('result_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('clicked_document_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clicked_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_history_user_created', 'search_history', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_table('user_collections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_collection_name')
    )
    op.create_index(op.f('ix_user_collections_user_id'), 'user_collections', ['user_id'], unique=False)
    op.create_table('user_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_reference', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notes_document_id'), 'user_notes', ['document_id'], unique=False)
    op.create_index('ix_user_notes_user_document', 'user_notes', ['user_id', 'document_id'], unique=False)
    op.create_index(op.f('ix_user_notes_user_id'), 'user_notes', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('favorite_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferred_answer_format', sa.Enum('CONCISE', 'DETAILED', 'BULLET_POINTS', name='answerformat', native_enum=False), nullable=False),
    sa.Column('default_top_k', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('collection_documents',
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['user_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'document_id')
    )
    op.create_table('conversation_documents',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'document_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieved_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider_used', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_table('conversation_documents')
    op.drop_table('collection_documents')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_notes_user_id'), table_name='user_notes')
    op.drop_index('ix_user_notes_user_document', table_name='user_notes')
    op.drop_index(op.f('ix_user_notes_document_id'), table_name='user_notes')
    op.drop_table('user_notes')
    op.drop_index(op.f('ix_user_collections_user_id'), table_name='user_collections')
    op.drop_table('user_collections')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_index('ix_search_history_user_created', table_name='search_history')
    op.drop_table('search_history')
    op.drop_index('ix_document_views_user_viewed', table_name='document_views')
    op.drop_index(op.f('ix_document_views_user_id'), table_name='document_views')
    op.drop_index('ix_document_views_user_document', table_name='document_views')
    op.drop_index(op.f('ix_document_views_document_id'), table_name='document_views')
    op.drop_table('document_views')
    op.drop_index('ix_document_chunks_section_type', table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_parent_chunk_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index('ix_document_chunks_content_tsv', table_name='document_chunks', postgresql_using='gin')
    op.drop_table('document_chunks')
    op.drop_table('document_authors')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('users')
    op.drop_index(op.f('ix_documents_primary_category'), table_name='documents')
    op.drop_index(op.f('ix_documents_arxiv_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_authors_normalized_name'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
